### ISSUE TITLE
fatal error LNK1120: 13 unresolved externals

### ISSUE THREAD

**Issue by abddabbour** [imbinwang/LINE2D#1]
Hi
I am trying to run your code folowing instractions you gave
but I got the following errors

could you please help me to solve this problem
notes:
I am working on windows 7 x64 visual studio 2017

regards

`1>------ Build started: Project: OpenGL-first, Configuration: Debug x64 ------
1>OfflineTemplatesLoader.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
1>ProtobufIO.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
1>Detector.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
1>GradientCalculator.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
1>GLMDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
1>MatchDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ)
1>ProtobufIO.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDH@Z)
1>Detector.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDH@Z)
1>GLMDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDH@Z)
1>MatchDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDH@Z)
1>OfflineTemplatesLoader.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDH@Z)
1>ProtobufIO.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QEAA@XZ)
1>Detector.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QEAA@XZ)
1>GLMDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QEAA@XZ)
1>MatchDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QEAA@XZ)
1>OfflineTemplatesLoader.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QEAA@XZ)
1>ProtobufIO.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)
1>Detector.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)
1>GLMDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)
1>MatchDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)
1>OfflineTemplatesLoader.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)
1>ProtobufIO.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
1>Detector.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
1>GLMDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
1>MatchDisplay.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
1>OfflineTemplatesLoader.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
1>GradientCalculator.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int,int)" (__imp_??0LogMessage@google@@QEAA@PEBDHH@Z) referenced in function "public: int __cdecl rl2d::GradientCalculator::compute(class cv::Mat const &,class cv::Mat &,class cv::Mat &)const " (?compute@GradientCalculator@rl2d@@QEBAHAEBVMat@cv@@AEAV34@1@Z)
1>GradientCalculator.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QEAA@XZ) referenced in function "public: int __cdecl rl2d::GradientCalculator::compute(class cv::Mat const &,class cv::Mat &,class cv::Mat &)const " (?compute@GradientCalculator@rl2d@@QEBAHAEBVMat@cv@@AEAV34@1@Z)
1>ProtobufIO.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (__imp_??0CheckOpMessageBuilder@base@google@@QEAA@PEBD@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>ProtobufIO.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)" (__imp_??1CheckOpMessageBuilder@base@google@@QEAA@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>ProtobufIO.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > * __cdecl google::base::CheckOpMessageBuilder::ForVar1(void)" (__imp_?ForVar1@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>ProtobufIO.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > * __cdecl google::base::CheckOpMessageBuilder::ForVar2(void)" (__imp_?ForVar2@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>ProtobufIO.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::base::CheckOpMessageBuilder::NewString(void)" (__imp_?NewString@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBH0PEBD@Z)
1>ProtobufIO.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageFatal::LogMessageFatal(char const *,int,struct google::CheckOpString const &)" (__imp_??0LogMessageFatal@google@@QEAA@PEBDHAEBUCheckOpString@1@@Z) referenced in function "bool __cdecl rl2d::ReadProtoFromBinaryFile(char const *,class google::protobuf::Message *)" (?ReadProtoFromBinaryFile@rl2d@@YA_NPEBDPEAVMessage@protobuf@google@@@Z)
1>C:\Users\Techno.Home\Documents\Visual Studio 2017\Projects\OpenGL-first\Debug\OpenGL-first.exe : fatal error LNK1120: 13 unresolved externals
1>Done building project "OpenGL-first.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by 1201721495** [comment]
Hello, can you tell me how can I use this project in VS2015（Windows10）? Thank you.

**Comment by 1201721495** [comment]
Hello, I met the same problem as you. Have you solved this problem?

**Comment by GuoChris** [comment]
You should add "GOOGLE_GLOG_DLL_DECL" in the preprocessor definition in project properties
